services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mailer
      MYSQL_USER: mailer_user
      MYSQL_PASSWORD: mailerpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build:
      context: .
      dockerfile: Dockerfile.php  # Use the custom Dockerfile
    container_name: php_container
    restart: unless-stopped
    volumes:
      - ./web:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  mariadb_data:
